import {test,expect,type Page} from '@playwright/test';
let pageErrors:string[]=[];test.beforeEach(async({page,context})=>{pageErrors=[];const capture=(target:Page)=>target.on('pageerror',e=>pageErrors.push(e.message));capture(page);context.on('page',capture);});test.afterEach(()=>expect(pageErrors).toEqual([]));
const wallet=(page:Page)=>page.evaluate(()=>(window as any).__HEXHOLD_TEST__.profile());
async function open(page:Page){await page.locator('#profile-open').click();await expect(page.locator('#profile-dialog')).toBeVisible();await expect(page.locator('#profile-dialog')).toHaveAttribute('aria-busy','false');}
async function fund(page:Page){await page.goto('/');await expect(page.locator('#menu-coins')).toHaveText('0');await page.evaluate(async()=>{const p=await (window as any).__HEXHOLD_TEST__.profile();p.coins=500;await new Promise<void>((resolve,reject)=>{const r=indexedDB.open('hexhold.player-profile',1);r.onsuccess=()=>{const db=r.result,tx=db.transaction('meta','readwrite');tx.objectStore('meta').put(p,'profile');tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>reject(tx.error);};});});await page.reload();await expect(page.locator('#menu-coins')).toHaveText('500');}
async function watchWrites(page:Page){await page.evaluate(()=>{const w=window as any;w.__PROFILE_WRITES__=[];const transaction=IDBDatabase.prototype.transaction,put=IDBObjectStore.prototype.put;IDBDatabase.prototype.transaction=function(...args:any[]){if(this.name==='hexhold.player-profile'&&args[1]!=='readonly'&&args[1]!==undefined)w.__PROFILE_WRITES__.push(args[1]);return transaction.apply(this,args as any);};IDBObjectStore.prototype.put=function(...args:any[]){if(this.transaction.db.name==='hexhold.player-profile')w.__PROFILE_WRITES__.push('put');return put.apply(this,args as any);};});}

test('new profile is readonly and fits all three mobile landscape viewports',async({browser})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});try{const page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#menu-coins')).toHaveText('0');const before=await wallet(page);await watchWrites(page);
  for(const size of [{width:844,height:390},{width:640,height:320},{width:568,height:320}]){
   await page.setViewportSize(size);await open(page);for(const [id,value] of Object.entries({'coins':'0','runs':'0','kills':'0','best':'0.0%','clears':'0','longest':'0.0초','markers':'1 / 20','colors':'1 / 17','marker-name':'기본 원','color-name':'내 기본색'}))await expect(page.locator('#profile-'+id)).toHaveText(value);
   await expect(page.locator('#profile-preview svg')).toBeVisible();
   for(const id of ['profile-close','profile-coins','profile-runs','profile-kills','profile-best','profile-clears','profile-longest','profile-markers','profile-colors','profile-marker-name','profile-color-name']){const b=(await page.locator('#'+id).boundingBox())!;expect(b.x,id).toBeGreaterThanOrEqual(0);expect(b.y,id).toBeGreaterThanOrEqual(0);expect(b.x+b.width,id).toBeLessThanOrEqual(size.width);expect(b.y+b.height,id).toBeLessThanOrEqual(size.height);}
   const overflow=await page.evaluate(()=>({document:document.documentElement.scrollHeight>innerHeight,dialog:document.getElementById('profile-dialog')!.scrollHeight-document.getElementById('profile-dialog')!.clientHeight,content:document.getElementById('profile-content')!.scrollHeight-document.getElementById('profile-content')!.clientHeight}));expect(overflow.document).toBe(false);expect(overflow.dialog).toBeLessThanOrEqual(1);expect(overflow.content).toBeLessThanOrEqual(1);
   await page.screenshot({path:'evidence/profile-v1-new-'+size.width+'x'+size.height+'.png'});await page.locator('#profile-close').click();await expect(page.locator('#profile-dialog')).not.toBeVisible();
  }expect(await wallet(page)).toEqual(before);expect(await page.evaluate(()=>(window as any).__PROFILE_WRITES__)).toEqual([]);expect(errors).toEqual([]);
 }finally{await context.close();}
});

test('actual death and Classic clear update saved profile totals and menu balance',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('hexhold.tutorialSeen','1'));await page.goto('/?experimentSeed=4');await page.getByTestId('practice').click();
 await page.evaluate(async()=>{const t=(window as any).__HEXHOLD_TEST__,s=t.getPractice();s.setPaused(true);s.match.participants[0].kills=3;const {markDead}=await import('/src/shared/life.ts' as string);markDead(s.match,s.match.participants[0],'WALL_HIT');t.showPracticeView();});await expect(page.locator('#run-coins')).toHaveText('+14');
 await page.locator('#run-retry').click();await page.evaluate(async()=>{const t=(window as any).__HEXHOLD_TEST__,s=t.getPractice(),m=s.match,h=m.participants[0];s.setPaused(true);const {setOwner}=await import('/src/shared/territory.ts' as string),{stepMatch}=await import('/src/shared/engine.ts' as string);for(const c of m.map.cells)setOwner(m,c.id,h.slot+1);stepMatch(m);t.showPracticeView();});await expect(page.locator('#run-title')).toHaveText('완전 점령!');await expect(page.locator('#run-coins')).toHaveText('+305');await page.locator('#run-menu').click();await expect(page.locator('#menu-coins')).toHaveText('319');
 await open(page);await expect(page.locator('#profile-coins')).toHaveText('319');await expect(page.locator('#profile-runs')).toHaveText('2');await expect(page.locator('#profile-kills')).toHaveText('3');await expect(page.locator('#profile-best')).toHaveText('100.0%');await expect(page.locator('#profile-clears')).toHaveText('1');await page.locator('#profile-close').click();await page.reload();await open(page);await expect(page.locator('#profile-coins')).toHaveText('319');await expect(page.locator('#profile-clears')).toHaveText('1');
});

test('shop purchases and Basic/IMAGE equipment immediately appear in profile with identical preview composition',async({page})=>{
 await fund(page);await page.locator('#shop-open').click();await page.locator('[data-product-id="ring"]').click();await page.locator('#shop-action').click();await expect(page.locator('#shop-action')).toHaveText('장착');await page.locator('#shop-action').click();await expect(page.locator('#shop-action')).toHaveText('장착 중');await page.locator('#shop-colors').click();await page.locator('[data-product-id="violet"]').click();await page.locator('#shop-action').click();await expect(page.locator('#shop-action')).toHaveText('장착');await page.locator('#shop-action').click();await expect(page.locator('#shop-action')).toHaveText('장착 중');await page.locator('#shop-close').click();await open(page);
 await expect(page.locator('#profile-marker-name')).toHaveText('링');await expect(page.locator('#profile-color-name')).toHaveText('바이올렛');await expect(page.locator('#profile-markers')).toHaveText('2 / 20');await expect(page.locator('#profile-colors')).toHaveText('2 / 17');await expect(page.locator('#profile-coins')).toHaveText('430');await expect(page.locator('#profile-preview svg [fill="#a180f4"]').first()).toBeVisible();await page.locator('#profile-close').click();
 await page.locator('#shop-open').click();await page.locator('[data-product-id="cat"]').click();await page.locator('#shop-action').click();await expect(page.locator('#shop-action')).toHaveText('장착');await page.locator('#shop-action').click();await expect(page.locator('#shop-action')).toHaveText('장착 중');await expect(page.locator('#shop-preview svg[data-marker-id]')).toBeVisible();
 const checksum=(node:any)=>node.outerHTML;const shopHash=await page.locator('#shop-preview svg').evaluate(checksum);await page.locator('#shop-close').click();await page.setViewportSize({width:568,height:320});await open(page);await expect(page.locator('#profile-marker-name')).toHaveText('말랑냥');await expect(page.locator('#profile-preview svg[data-marker-id]')).toBeVisible();expect(await page.locator('#profile-preview svg').evaluate(checksum)).toBe(shopHash);await expect(page.locator('#profile-markers')).toHaveText('3 / 20');await expect(page.locator('#profile-coins')).toHaveText('380');for(const id of ['profile-close','profile-markers','profile-colors','profile-marker-name','profile-color-name']){const box=(await page.locator('#'+id).boundingBox())!;expect(box.x+box.width).toBeLessThanOrEqual(568);expect(box.y+box.height).toBeLessThanOrEqual(320);}expect(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight)).toBe(false);await page.screenshot({path:'evidence/profile-v1-equipped.png'});await page.locator('#profile-close').click();await page.reload();await open(page);await expect(page.locator('#profile-marker-name')).toHaveText('말랑냥');await expect(page.locator('#profile-color-name')).toHaveText('바이올렛');await expect(page.locator('#profile-coins')).toHaveText('380');
});

test('an open profile receives reward, purchase and equipment changes through existing BroadcastChannel',async({context})=>{
 const a=await context.newPage(),b=await context.newPage();await Promise.all([a.goto('/'),b.goto('/')]);await expect(a.locator('#menu-coins')).toHaveText('0');await open(a);
 await b.evaluate(async()=>{const {ProfileStore}=await import('/src/client/profile-store.ts' as string),s=new ProfileStore();try{const admission={matchId:'profile-tabs',participantId:'h',lifeId:1,initialTerritoryCells:7,ownerId:'tab'};await s.admit(admission);await s.grant({runId:'profile-tabs:h:life:1',matchId:'profile-tabs',participantId:'h',lifeId:1,endReason:'DEATH',startedAtTick:0,endedAtTick:300,durationTicks:300,simulationHz:30,mapCellCount:1000,bestTerritoryCells:300,bestTerritoryPercent:30,kills:2});await s.purchase('marker','ring');await s.equip('marker','ring');await s.purchase('marker-color','coral');await s.equip('marker-color','coral');}finally{s.dispose();}});
 await expect(a.locator('#profile-coins')).toHaveText('1');await expect(a.locator('#menu-coins')).toHaveText('1');await expect(a.locator('#profile-runs')).toHaveText('1');await expect(a.locator('#profile-kills')).toHaveText('2');await expect(a.locator('#profile-best')).toHaveText('30.0%');await expect(a.locator('#profile-longest')).toHaveText('10.0초');await expect(a.locator('#profile-marker-name')).toHaveText('링');await expect(a.locator('#profile-color-name')).toHaveText('코랄');await expect(a.locator('#profile-markers')).toHaveText('2 / 20');
});

test('profile storage failure keeps close/retry usable and recovery never writes',async({page})=>{
 await fund(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.evaluate(()=>{const w=window as any;w.__PROFILE_FACTORY__=indexedDB;Object.defineProperty(window,'indexedDB',{configurable:true,get(){throw Error('Storage denied');}});});await open(page);await expect(page.locator('#profile-status')).toContainText('저장소를 읽지 못');await expect(page.locator('#profile-coins')).toHaveText('읽기 불가');await expect(page.locator('#profile-content')).toBeHidden();await expect(page.locator('#profile-close')).toBeVisible();
 await page.evaluate(()=>Object.defineProperty(window,'indexedDB',{configurable:true,value:(window as any).__PROFILE_FACTORY__}));await watchWrites(page);await page.locator('#profile-reload').click();await expect(page.locator('#profile-coins')).toHaveText('500');await expect(page.locator('#profile-reload')).toBeHidden();await page.keyboard.press('Escape');await expect(page.locator('#profile-dialog')).not.toBeVisible();expect(await page.evaluate(()=>(window as any).__PROFILE_WRITES__)).toEqual([]);expect(errors).toEqual([]);
});

test('display snapshots never create missing databases, persist migration or reset corrupt profiles',async({page})=>{
 await page.goto('/');const result=await page.evaluate(async()=>{const {ProfileStore}=await import('/src/client/profile-store.ts' as string),{emptyProfile}=await import('/src/client/profile.ts' as string);
  const missingName='profile-display-absent',missing=new ProfileStore(indexedDB,missingName),fresh=await missing.readForDisplay();missing.dispose();const absent=!(await indexedDB.databases()).some(db=>db.name===missingName);
  const legacy=emptyProfile() as any;delete legacy.inventory;legacy.coins=777;legacy.stats.totalKills=12;
  async function seed(name:string,value:any){await new Promise<void>((resolve,reject)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>r.result.createObjectStore('meta');r.onsuccess=()=>{const db=r.result,tx=db.transaction('meta','readwrite');tx.objectStore('meta').put(value,'profile');tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>reject(tx.error);};});}
  async function raw(name:string){return new Promise<any>((resolve,reject)=>{const r=indexedDB.open(name);r.onsuccess=()=>{const db=r.result,tx=db.transaction('meta','readonly'),get=tx.objectStore('meta').get('profile');let value:any;get.onsuccess=()=>value=get.result;tx.oncomplete=()=>{db.close();resolve(value);};tx.onabort=()=>reject(tx.error);};});}
  await seed('profile-display-legacy',legacy);const old=new ProfileStore(indexedDB,'profile-display-legacy'),view=await old.readForDisplay();old.dispose();const unchanged=await raw('profile-display-legacy');
  const corrupt={version:1,coins:-1};await seed('profile-display-corrupt',corrupt);const bad=new ProfileStore(indexedDB,'profile-display-corrupt');let failed=false;try{await bad.readForDisplay();}catch{failed=true;}bad.dispose();return{fresh,absent,legacy,view,unchanged,corrupt,corruptAfter:await raw('profile-display-corrupt'),failed};
 });expect(result.fresh.coins).toBe(0);expect(result.absent).toBe(true);expect(result.view.coins).toBe(777);expect(result.view.stats.totalKills).toBe(12);expect(result.view.inventory.equippedMarkerId).toBe('default');expect(result.unchanged).toEqual(result.legacy);expect(result.failed).toBe(true);expect(result.corruptAfter).toEqual(result.corrupt);
});


test('large persisted numbers fit the smallest landscape without hiding Collection or close',async({page})=>{
 await page.setViewportSize({width:568,height:320});await fund(page);await page.evaluate(async()=>{const p=await (window as any).__HEXHOLD_TEST__.profile();p.coins=Number.MAX_SAFE_INTEGER;p.stats={runsPlayed:Number.MAX_SAFE_INTEGER,totalKills:Number.MAX_SAFE_INTEGER,classicClears:Number.MAX_SAFE_INTEGER,bestTerritoryPercent:100,longestRunSeconds:86400};await new Promise<void>(resolve=>{const r=indexedDB.open('hexhold.player-profile');r.onsuccess=()=>{const db=r.result,tx=db.transaction('meta','readwrite');tx.objectStore('meta').put(p,'profile');tx.oncomplete=()=>{db.close();resolve();};};});});
 await open(page);await expect(page.locator('#profile-runs')).toHaveText(Number.MAX_SAFE_INTEGER.toLocaleString());await expect(page.locator('#profile-coins')).toHaveText(Number.MAX_SAFE_INTEGER.toLocaleString());
 for(const id of ['profile-close','profile-runs','profile-kills','profile-clears','profile-markers','profile-colors'])expect(await page.locator('#'+id).evaluate(e=>e.scrollWidth-e.clientWidth)).toBeLessThanOrEqual(1);
 expect(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight)).toBe(false);await page.locator('#profile-close').click();
});
