import {test,expect} from '@playwright/test';
test('real IndexedDB serializes tabs, survives reload, bounds history and recovers corrupt storage',async({page})=>{
 await page.goto('/');const values=await page.evaluate(async()=>{
 const {ProfileStore}=await import('/src/client/profile-store.ts' as string);const a=new ProfileStore(indexedDB,'reward-test'),b=new ProfileStore(indexedDB,'reward-test');
 const r={runId:'world:h:life:1',matchId:'world',participantId:'h',lifeId:1,endReason:'DEATH',startedAtTick:0,endedAtTick:300,durationTicks:300,simulationHz:30,mapCellCount:1000,kills:3,bestTerritoryCells:187,bestTerritoryPercent:18.7};
 await a.admit({matchId:'world',participantId:'h',lifeId:1,initialTerritoryCells:7,ownerId:'a'});const grants=await Promise.all([a.grant(r),b.grant(r)]);
 await a.admit({matchId:'world',participantId:'h',lifeId:2,initialTerritoryCells:7,ownerId:'a'});const beforeAbort=await a.read(),put=IDBObjectStore.prototype.put;let aborted=false;IDBObjectStore.prototype.put=function(){throw new DOMException('Quota full','QuotaExceededError');};try{await a.grant({...r,lifeId:2,runId:'world:h:life:2'});}catch{aborted=true;}finally{IDBObjectStore.prototype.put=put;}const afterAbort=await a.read();if(!aborted||JSON.stringify(beforeAbort)!==JSON.stringify(afterAbort))throw new Error('Non-atomic aborted reward');
 const bad=new ProfileStore(null,'unavailable');let failed=false;try{await bad.grant(r);}catch{failed=true;}bad.dispose();const profile=await b.read();a.dispose();b.dispose();return{grants,profile,failed};});
 expect(values.grants.map((r:any)=>r.status).sort()).toEqual(['duplicate','granted']);expect(values.profile.coins).toBe(51);expect(values.profile.stats.runsPlayed).toBe(1);expect(values.failed).toBe(true);
 await page.reload();const restored=await page.evaluate(async()=>{const {ProfileStore}=await import('/src/client/profile-store.ts' as string);const s=new ProfileStore(indexedDB,'reward-test');const p=await s.read();s.dispose();return p;});expect(restored).toEqual(values.profile);
 const stress=await page.evaluate(async()=>{const {ProfileStore}=await import('/src/client/profile-store.ts' as string);const s=new ProfileStore(indexedDB,'reward-stress');const admission=(lifeId:number)=>({matchId:'m',participantId:'h',lifeId,initialTerritoryCells:7,ownerId:'tab'});const result=(lifeId:number)=>({runId:'m:h:life:'+lifeId,matchId:'m',participantId:'h',lifeId,endReason:'DEATH',startedAtTick:0,endedAtTick:30,durationTicks:30,simulationHz:30,mapCellCount:1000,kills:0,bestTerritoryCells:30,bestTerritoryPercent:3.0});const {emptyProfile,grantProfileReward}=await import('/src/client/profile.ts' as string);const seeded=emptyProfile();for(let i=1;i<=270;i++)grantProfileReward(seeded,result(i),admission(i));await s.read();await new Promise<void>((resolve,reject)=>{const req=indexedDB.open('reward-stress',1);req.onsuccess=()=>{const db=req.result,tx=db.transaction('meta','readwrite');tx.objectStore('meta').put(seeded,'profile');tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>reject(tx.error);};});const duplicate=await s.grant(result(1));const p=await s.read();s.dispose();return{duplicate,p};});expect(stress.p.processedRuns).toHaveLength(256);expect(stress.p.coins).toBe(2970);expect(stress.duplicate.status).toBe('duplicate');
 const recovered=await page.evaluate(async()=>{const {ProfileStore,PROFILE_STORE,PROFILE_KEY}=await import('/src/client/profile-store.ts' as string);const s=new ProfileStore(indexedDB,'reward-corrupt');await s.read();s.dispose();await new Promise<void>((resolve,reject)=>{const req=indexedDB.open('reward-corrupt',1);req.onsuccess=()=>{const db=req.result,tx=db.transaction(PROFILE_STORE,'readwrite');tx.objectStore(PROFILE_STORE).put({version:1,coins:-10},PROFILE_KEY);tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>reject(tx.error);};});const fresh=new ProfileStore(indexedDB,'reward-corrupt');const p=await fresh.read();fresh.dispose();return p;});expect(recovered.coins).toBe(0);expect(recovered.stats.runsPlayed).toBe(0);
});
test('actual practice rewards, default capture, same-world retry and compact result UI',async({browser})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});await context.addInitScript(()=>localStorage.setItem('hexhold.tutorialSeen','1'));try{const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?experimentSeed=4');await page.getByTestId('practice').click();
 await expect.poll(()=>page.evaluate(()=>(window as any).__HEXHOLD_TEST__.getCaptureEffectState().style)).toBe('CAPTURE_PULSE');
 const world=await page.evaluate(async()=>{const t=(window as any).__HEXHOLD_TEST__,s=t.getPractice(),m=s.match,h=m.participants[0];s.setPaused(true);h.kills=3;const {markDead}=await import('/src/shared/life.ts' as string);markDead(m,h,'WALL_HIT');t.showPracticeView();return m.matchId;});
 await expect(page.locator('#run-coins')).toHaveText('+14 Coins');await expect(page.locator('#run-results')).toBeVisible();
 for(const viewport of [{width:844,height:390},{width:640,height:320}]){await page.setViewportSize(viewport);for(const id of ['run-title','run-best','run-time','run-kills','run-coins','run-balance','run-retry','run-menu']){const b=(await page.locator('#'+id).boundingBox())!;expect(b.y).toBeGreaterThanOrEqual(0);expect(b.y+b.height).toBeLessThanOrEqual(viewport.height);}expect(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight)).toBe(false);}
 await page.screenshot({path:'evidence/reward-death-landscape.png'});let p=await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.profile());expect(p.coins).toBe(14);expect(p.stats.runsPlayed).toBe(1);
 await page.locator('#run-retry').click();expect(await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.getPractice().match.matchId)).toBe(world);
 await page.evaluate(async()=>{const t=(window as any).__HEXHOLD_TEST__,s=t.getPractice(),m=s.match,h=m.participants[0];s.setPaused(true);const {setOwner}=await import('/src/shared/territory.ts' as string),{stepMatch}=await import('/src/shared/engine.ts' as string);for(const c of m.map.cells)setOwner(m,c.id,h.slot+1);stepMatch(m);t.showPracticeView();});await expect(page.locator('#run-title')).toHaveText('CLASSIC CLEAR!');await expect(page.locator('#run-coins')).toHaveText('+305 Coins');await page.screenshot({path:'evidence/reward-clear-landscape.png'});
 p=await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.profile());expect(p.coins).toBe(319);expect(p.stats).toMatchObject({runsPlayed:2,classicClears:1,totalKills:3,bestTerritoryPercent:100});await page.locator('#run-menu').click();await expect(page.locator('#menu-coins')).toHaveText('Coins · 319');await page.reload();await expect(page.locator('#menu-coins')).toHaveText('Coins · 319');expect(errors).toEqual([]);
 }finally{await context.close();}
});
test('storage failure leaves result usable and exposes save retry without a fake grant',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('hexhold.tutorialSeen','1');(window as any).__RESTORE_PROFILE_DB__=indexedDB;Object.defineProperty(window,'indexedDB',{get(){throw new Error('blocked');}});});await page.goto('/');await page.getByTestId('practice').click();
 await page.evaluate(async()=>{const t=(window as any).__HEXHOLD_TEST__,s=t.getPractice();s.setPaused(true);const {markDead}=await import('/src/shared/life.ts' as string);markDead(s.match,s.match.participants[0],'WALL_HIT');t.showPracticeView();});await expect(page.locator('#run-coins')).toHaveText('저장 실패');await expect(page.locator('#reward-retry')).toBeVisible();await page.locator('#reward-retry').click();await expect(page.locator('#run-coins')).toHaveText('저장 실패');await page.evaluate(()=>Object.defineProperty(window,'indexedDB',{value:(window as any).__RESTORE_PROFILE_DB__}));await page.locator('#reward-retry').click();await expect(page.locator('#run-coins')).toHaveText('+0 Coins');await expect(page.locator('#reward-retry')).toBeHidden();expect((await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.profile())).stats.runsPlayed).toBe(1);await page.locator('#run-retry').click();await expect(page.locator('#hud')).toBeVisible();
});

test('separate browser tabs grant one Run once and retry a failed transaction',async({context})=>{
 const a=await context.newPage(),b=await context.newPage();await Promise.all([a.goto('/'),b.goto('/')]);
 const seed=async()=>{const {ProfileStore}=await import('/src/client/profile-store.ts' as string);const s=new ProfileStore(indexedDB,'reward-tabs');await s.admit({matchId:'tabs',participantId:'h',lifeId:1,initialTerritoryCells:7,ownerId:'tab'});s.dispose();};await a.evaluate(seed);
 const grant=async()=>{const {ProfileStore}=await import('/src/client/profile-store.ts' as string);const s=new ProfileStore(indexedDB,'reward-tabs');try{return await s.grant({runId:'tabs:h:life:1',matchId:'tabs',participantId:'h',lifeId:1,endReason:'DEATH',startedAtTick:0,endedAtTick:30,durationTicks:30,simulationHz:30,mapCellCount:1000,kills:3,bestTerritoryCells:187,bestTerritoryPercent:18.7});}finally{s.dispose();}};
 const receipts=await Promise.all([a.evaluate(grant),b.evaluate(grant)]);expect(receipts.map((r:any)=>r.status).sort()).toEqual(['duplicate','granted']);
 const retried=await a.evaluate(async()=>{const {ProfileStore}=await import('/src/client/profile-store.ts' as string);const s=new ProfileStore(indexedDB,'reward-tabs');await s.admit({matchId:'tabs',participantId:'h',lifeId:2,initialTerritoryCells:7,ownerId:'tab'});const r={runId:'tabs:h:life:2',matchId:'tabs',participantId:'h',lifeId:2,endReason:'DEATH',startedAtTick:0,endedAtTick:30,durationTicks:30,simulationHz:30,mapCellCount:1000,kills:0,bestTerritoryCells:30,bestTerritoryPercent:3.0},put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('Quota full','QuotaExceededError');};try{await s.grant(r);}catch{}finally{IDBObjectStore.prototype.put=put;}const recovered=await s.grant(r),duplicate=await s.grant(r),p=await s.read();s.dispose();return{recovered,duplicate,p};});expect(retried.recovered.status).toBe('granted');expect(retried.duplicate.status).toBe('duplicate');expect(retried.p.coins).toBe(62);expect(retried.p.stats.runsPlayed).toBe(2);
});
