import {createGameServer} from '../../src/server/app.js';
import {markDead} from '../../src/shared/life.js';
import {until} from '../server/helpers.js';
import {test,expect} from '@playwright/test';
test('single-player Run ends after collapse, freezes and retries elsewhere in the same R56/16 world',async({browser})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const errors:string[]=[];
 await context.addInitScript(()=>{localStorage.setItem('hexhold.tutorialSeen','1');Object.defineProperty(crypto,'randomUUID',{value:undefined});});try{const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('/?experimentSeed=4');await page.getByTestId('practice').click();
 const before=await page.evaluate(()=>{const t=(window as any).__HEXHOLD_TEST__,s=t.getPractice(),m=s.match,p=m.participants[0];s.setPaused(true);return{matchId:m.matchId,lifeId:p.lifeId,spawn:[...p.spawnCells],bots:m.participants.slice(1).map((b:any)=>b.participantId),config:m.config};});expect(before.config).toMatchObject({mapRadius:56,maxSlots:16,spawnRadius:1});
 await page.evaluate(()=>{const s=(window as any).__HEXHOLD_TEST__.getPractice(),m=s.match,p=m.participants[0],c=m.map.cells[m.map.byKey.get('56,0')];p.cellId=c.id;p.position={...c.center};p.direction={x:1,y:0};p.targetDirection=null;p.protectedUntilTick=0;s.setDirection({x:1,y:0});s.setPaused(false);s.advance(10000);s.advance(10034);});
 await expect(page.locator('#run-results')).toBeHidden();await expect(page.locator('#run-results')).toBeVisible();await expect(page.locator('#run-title')).toHaveText('RUN OVER');
 expect(await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.getTerritoryEffectState().active)).toBe(0);
 const ended=await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.getPractice().match.tick);await page.waitForTimeout(300);expect(await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.getPractice().match.tick)).toBe(ended);
 for(const viewport of [{width:844,height:390},{width:640,height:320}]){await page.setViewportSize(viewport);for(const id of ['#run-title','#run-best','#run-time','#run-kills','#run-retry','#run-menu']){const b=(await page.locator(id).boundingBox())!;expect(b.y).toBeGreaterThanOrEqual(0);expect(b.y+b.height).toBeLessThanOrEqual(viewport.height);}expect(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight)).toBe(false);}
 await page.screenshot({path:'evidence/run-end-death-landscape.png'});await page.locator('#run-retry').click();await expect(page.locator('#run-results')).toBeHidden();await expect(page.locator('#hud')).toBeVisible();
 const next=await page.evaluate(()=>{const s=(window as any).__HEXHOLD_TEST__.getPractice();s.setPaused(true);const m=s.match,p=m.participants[0];return{matchId:m.matchId,lifeId:p.lifeId,spawn:[...p.spawnCells],bots:m.participants.slice(1).map((b:any)=>b.participantId),run:p.run};});expect(next.matchId).toBe(before.matchId);expect(next.lifeId).toBe(before.lifeId+1);expect(next.bots).toEqual(before.bots);expect(next.spawn).toHaveLength(7);expect(next.spawn.some((id:number)=>before.spawn.includes(id))).toBe(false);expect(next.run.result).toBeNull();
 await page.evaluate(async()=>{const s=(window as any).__HEXHOLD_TEST__.getPractice(),m=s.match,p=m.participants[0];const territory=await import('/src/shared/territory.ts' as string),engine=await import('/src/shared/engine.ts' as string);for(const c of m.map.cells)territory.setOwner(m,c.id,p.slot+1);engine.stepMatch(m);(window as any).__HEXHOLD_TEST__.showPracticeView();});
 await expect(page.locator('#run-title')).toHaveText('CLASSIC CLEAR!');await expect(page.locator('#run-best')).toHaveText('100.0%');await page.screenshot({path:'evidence/run-end-clear-landscape.png'});await page.locator('#run-retry').click();expect(await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.getPractice().match.matchId)).not.toBe(before.matchId);await page.getByTestId('leave').click();expect(errors).toEqual([]);
 }finally{await context.close();}
});
test('online death results recover and the explicit retry keeps the current world',async({browser})=>{
 process.env.NODE_ENV='test';let now=0;const f=createGameServer({autoStart:false,now:()=>now,seed:()=>4});await new Promise<void>(r=>f.http.listen(3002,'127.0.0.1',r));
 const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});await context.addInitScript(()=>localStorage.setItem('hexhold.tutorialSeen','1'));try{
 const page=await context.newPage();await page.goto('/');await page.getByTestId('create').click();await page.getByTestId('start').click();await until(()=>[...f.rooms.rooms.values()][0]?.phase==='COUNTDOWN');now=3000;f.loop.pump();await expect(page.locator('#hud')).toBeVisible();
 const room=[...f.rooms.rooms.values()][0],m=room.match!,p=m.participants[0],bots=m.participants.slice(1).map(b=>b.participantId);markDead(m,p,'WALL_HIT');const result=structuredClone(p.run!.result);f.loop.publishSnapshot(room,false,true);
 await expect(page.locator('#run-results')).toBeHidden();await expect(page.locator('#run-results')).toBeVisible();expect(await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.enabled())).toBe(false);
 const beforeReconnect=await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.history.length);await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.transportClose(false));await expect(page.locator('#run-retry')).toBeDisabled();await until(()=>![...f.sessions.sessions.values()][0].connected);now+=100;f.loop.pump();await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.reconnect());await expect.poll(()=>page.evaluate(()=>(window as any).__HEXHOLD_TEST__.history.length),{timeout:15000}).toBeGreaterThan(beforeReconnect);await expect(page.locator('#run-retry')).toBeEnabled();await expect(page.locator('#run-results')).toBeVisible();
 await expect.poll(()=>page.evaluate(()=>(window as any).__HEXHOLD_TEST__.getView().participants.find((p:any)=>p.kind==='HUMAN').run.result)).toEqual(result);
 await page.locator('#run-retry').click();await expect.poll(()=>p.lifeId).toBe(2);await expect(page.locator('#run-results')).toBeHidden();await expect(page.locator('#hud')).toBeVisible();expect(room.match).toBe(m);expect(p.lifeId).toBe(2);expect(p.run!.result).toBeNull();expect(m.participants.slice(1).map(b=>b.participantId)).toEqual(bots);expect(await page.evaluate(()=>(window as any).__HEXHOLD_TEST__.enabled())).toBe(true);
 }finally{await context.close();await f.close();}
});
